import type { Product } from "@/types/product";

/**
 * Placeholder 3D assets: Google's public model-viewer sample models
 * (https://modelviewer.dev/shared-assets/models/) — swap `modelGlbUrl`
 * for real product scans in production. See README section "อัปโหลดโมเดล 3D".
 */
const SAMPLE_GLB = {
  astronaut: "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  robot: "https://modelviewer.dev/shared-assets/models/RobotExpressive.glb",
  helmet: "https://modelviewer.dev/shared-assets/models/NeilArmstrong.glb",
};

const now = new Date().toISOString();

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Vertex Pro Gaming Mouse",
    slug: "vertex-pro-gaming-mouse",
    shortDescription: "เมาส์เกมมิงน้ำหนักเบา เซนเซอร์ความแม่นยำสูง",
    description:
      "Vertex Pro ออกแบบมาสำหรับเกมเมอร์สาย FPS ด้วยเซนเซอร์ออปติคัลความละเอียดสูง ปุ่มกดตอบสนองไว น้ำหนักเบาเพียง 62 กรัม พร้อมไฟ RGB ปรับแต่งได้ผ่านซอฟต์แวร์",
    brand: "Vertex",
    category: "อุปกรณ์เกมมิง",
    categorySlug: "gaming",
    status: "active",
    basePrice: 1990,
    compareAtPrice: 2490,
    sku: "VTX-MSE-001",
    stockQuantity: 42,
    lowStockThreshold: 10,
    isFeatured: true,
    isBestseller: true,
    isNew: false,
    supports3d: false,
    supports360: true,
    supportsAr: false,
    modelGlbUrl: null,
    modelUsdzUrl: null,
    fallbackImageUrl:
      "https://images.unsplash.com/photo-1527814050087-3793815479db?w=1200&q=80",
    images: [
      {
        id: "img1",
        productId: "p1",
        url: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=1200&q=80",
        altText: "Vertex Pro Gaming Mouse",
        sortOrder: 0,
        isPrimary: true,
      },
      {
        id: "img1b",
        productId: "p1",
        url: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=1200&q=80",
        altText: "Vertex Pro Gaming Mouse side",
        sortOrder: 1,
        isPrimary: false,
      },
    ],
    options: [
      {
        id: "opt1",
        productId: "p1",
        name: "สี",
        displayType: "color",
        sortOrder: 0,
        values: [
          { id: "ov1", optionId: "opt1", value: "ดำ", colorHex: "#1a1d24", sortOrder: 0 },
          { id: "ov2", optionId: "opt1", value: "ขาว", colorHex: "#f1f5f9", sortOrder: 1 },
        ],
      },
    ],
    variants: [
      { id: "v1", productId: "p1", sku: "VTX-MSE-001-BLK", price: 1990, compareAtPrice: 2490, stockQuantity: 30, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov1"] },
      { id: "v2", productId: "p1", sku: "VTX-MSE-001-WHT", price: 1990, compareAtPrice: 2490, stockQuantity: 12, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov2"] },
    ],
    hotspots: [],
    threeSixty: { frameCount: 24, frames: Array.from({ length: 24 }, (_, i) => `/product-360/gaming-mouse/frame-${String(i + 1).padStart(3, "0")}.webp`) },
    specs: [
      { label: "เซนเซอร์", value: "26,000 DPI Optical" },
      { label: "น้ำหนัก", value: "62 กรัม" },
      { label: "การเชื่อมต่อ", value: "USB-C แบบมีสาย / ไร้สาย 2.4GHz" },
      { label: "อายุการใช้งานสวิตช์", value: "80 ล้านครั้ง" },
    ],
    dimensions: { widthCm: 6.2, heightCm: 3.8, depthCm: 11.8, weightKg: 0.062 },
    reviewSummary: { average: 4.7, count: 128 },
    soldCount: 860,
    shippingEtaDays: [1, 3],
    createdAt: now,
  },
  {
    id: "p2",
    name: "Aurora Mechanical Keyboard 75%",
    slug: "aurora-mechanical-keyboard-75",
    shortDescription: "คีย์บอร์ดกลไก Hot-swap พร้อมไฟ RGB ต่อบลูทูธได้ 3 อุปกรณ์",
    description:
      "Aurora มาพร้อม Gasket Mount ให้สัมผัสการพิมพ์นุ่มนวล รองรับสวิตช์แบบ Hot-swap เปลี่ยนได้โดยไม่ต้องบัดกรี ตัวเรือนอะลูมิเนียม CNC แข็งแรงทนทาน",
    brand: "Aurora",
    category: "อุปกรณ์เกมมิง",
    categorySlug: "gaming",
    status: "active",
    basePrice: 3290,
    compareAtPrice: null,
    sku: "AUR-KB-075",
    stockQuantity: 25,
    lowStockThreshold: 8,
    isFeatured: true,
    isBestseller: false,
    isNew: true,
    supports3d: true,
    supports360: false,
    supportsAr: true,
    modelGlbUrl: SAMPLE_GLB.robot,
    modelUsdzUrl: null,
    fallbackImageUrl:
      "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=1200&q=80",
    images: [
      {
        id: "img2",
        productId: "p2",
        url: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=1200&q=80",
        altText: "Aurora Mechanical Keyboard",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    options: [
      {
        id: "opt2",
        productId: "p2",
        name: "สวิตช์",
        displayType: "buttons",
        sortOrder: 0,
        values: [
          { id: "ov3", optionId: "opt2", value: "Linear แดง", sortOrder: 0 },
          { id: "ov4", optionId: "opt2", value: "Tactile น้ำตาล", sortOrder: 1 },
        ],
      },
    ],
    variants: [
      { id: "v3", productId: "p2", sku: "AUR-KB-075-RED", price: 3290, compareAtPrice: null, stockQuantity: 15, imageUrl: null, modelUrl: SAMPLE_GLB.robot, isActive: true, optionValueIds: ["ov3"] },
      { id: "v4", productId: "p2", sku: "AUR-KB-075-BRN", price: 3390, compareAtPrice: null, stockQuantity: 10, imageUrl: null, modelUrl: SAMPLE_GLB.robot, isActive: true, optionValueIds: ["ov4"] },
    ],
    hotspots: [
      { id: "h1", productId: "p2", title: "โครงอะลูมิเนียม CNC", description: "ตัวเรือนกัด CNC จากอะลูมิเนียมเกรดการบิน ให้น้ำหนักแน่นและเสียงพิมพ์แน่นหนึบ", position: { x: 0.1, y: 0.4, z: 0.2 }, normal: { x: 0, y: 1, z: 0 }, icon: "Layers", sortOrder: 0, isActive: true },
      { id: "h2", productId: "p2", title: "พอร์ต USB-C", description: "เชื่อมต่อสายถอดได้ พร้อมช่องเก็บสายใต้ตัวเครื่อง", position: { x: -0.3, y: 0.1, z: 0.4 }, normal: { x: 0, y: 0, z: 1 }, icon: "Usb", sortOrder: 1, isActive: true },
      { id: "h3", productId: "p2", title: "Hot-swap Socket", description: "เปลี่ยนสวิตช์ได้เองโดยไม่ต้องบัดกรี รองรับสวิตช์ 3 และ 5 พิน", position: { x: 0.2, y: 0.3, z: -0.1 }, normal: { x: 0, y: 1, z: 0 }, icon: "MousePointerClick", sortOrder: 2, isActive: true },
    ],
    threeSixty: null,
    materialOptions: [
      { id: "mat-black", name: "ดำเงา", color: "#15171c", roughness: 0.35, metalness: 0.6 },
      { id: "mat-white", name: "ขาวมุก", color: "#f1f3f6", roughness: 0.4, metalness: 0.2 },
      { id: "mat-navy", name: "น้ำเงินเข้ม", color: "#1d3a63", roughness: 0.3, metalness: 0.5 },
      { id: "mat-red", name: "แดงเลือดหมู", color: "#7f1d1d", roughness: 0.35, metalness: 0.4 },
    ],
    specs: [
      { label: "เค้าโครง", value: "75% (84 ปุ่ม)" },
      { label: "การเชื่อมต่อ", value: "Bluetooth 5.1 / USB-C / 2.4GHz" },
      { label: "แบตเตอรี่", value: "4000mAh ใช้งานได้นานสูงสุด 200 ชม." },
      { label: "น้ำหนัก", value: "980 กรัม" },
    ],
    dimensions: { widthCm: 32.5, heightCm: 3.8, depthCm: 13.6, weightKg: 0.98 },
    reviewSummary: { average: 4.9, count: 76 },
    soldCount: 340,
    shippingEtaDays: [2, 4],
    createdAt: now,
  },
  {
    id: "p3",
    name: "Nimbus Wireless Headphones",
    slug: "nimbus-wireless-headphones",
    shortDescription: "หูฟังไร้สายตัดเสียงรบกวน เบสหนักแน่น แบตอึด 40 ชม.",
    description:
      "Nimbus มาพร้อมไดร์เวอร์ขนาด 40 มม. ให้เสียงคมชัดทุกย่าน ระบบ ANC ตัดเสียงรบกวนได้สูงสุด 35dB เบาสบายสวมใส่ได้ทั้งวัน",
    brand: "Nimbus Audio",
    category: "หูฟังและลำโพง",
    categorySlug: "audio",
    status: "active",
    basePrice: 2590,
    compareAtPrice: 3290,
    sku: "NMB-HDP-001",
    stockQuantity: 60,
    lowStockThreshold: 15,
    isFeatured: true,
    isBestseller: true,
    isNew: false,
    supports3d: false,
    supports360: false,
    supportsAr: false,
    modelGlbUrl: null,
    modelUsdzUrl: null,
    fallbackImageUrl:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&q=80",
    images: [
      { id: "img3", productId: "p3", url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&q=80", altText: "Nimbus Wireless Headphones", sortOrder: 0, isPrimary: true },
      { id: "img3b", productId: "p3", url: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=1200&q=80", altText: "Nimbus side", sortOrder: 1, isPrimary: false },
    ],
    options: [
      { id: "opt3", productId: "p3", name: "สี", displayType: "color", sortOrder: 0, values: [
        { id: "ov5", optionId: "opt3", value: "ดำเงา", colorHex: "#111318", sortOrder: 0 },
        { id: "ov6", optionId: "opt3", value: "เบจ", colorHex: "#d8c3a5", sortOrder: 1 },
      ]},
    ],
    variants: [
      { id: "v5", productId: "p3", sku: "NMB-HDP-001-BLK", price: 2590, compareAtPrice: 3290, stockQuantity: 40, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov5"] },
      { id: "v6", productId: "p3", sku: "NMB-HDP-001-BGE", price: 2590, compareAtPrice: 3290, stockQuantity: 20, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov6"] },
    ],
    hotspots: [],
    threeSixty: null,
    specs: [
      { label: "ไดร์เวอร์", value: "40 มม. Dynamic" },
      { label: "แบตเตอรี่", value: "40 ชั่วโมง (เปิด ANC 28 ชม.)" },
      { label: "การเชื่อมต่อ", value: "Bluetooth 5.3, 3.5mm" },
      { label: "น้ำหนัก", value: "260 กรัม" },
    ],
    dimensions: { widthCm: 18, heightCm: 20, depthCm: 8, weightKg: 0.26 },
    reviewSummary: { average: 4.6, count: 214 },
    soldCount: 1250,
    shippingEtaDays: [1, 3],
    createdAt: now,
  },
  {
    id: "p4",
    name: "Halo X13 Smartphone",
    slug: "halo-x13-smartphone",
    shortDescription: "จอ AMOLED 120Hz กล้องสามตัว ชิปประมวลผลแรงระดับเรือธง",
    description:
      "Halo X13 มาพร้อมจอ AMOLED 6.7 นิ้ว รีเฟรชเรต 120Hz กล้องหลัก 3 ตัวคมชัดทุกสภาพแสง แบตเตอรี่ 5000mAh ชาร์จเร็ว 67W",
    brand: "Halo",
    category: "โทรศัพท์และแท็บเล็ต",
    categorySlug: "phones-tablets",
    status: "active",
    basePrice: 21990,
    compareAtPrice: 24990,
    sku: "HLO-X13-256",
    stockQuantity: 18,
    lowStockThreshold: 5,
    isFeatured: true,
    isBestseller: true,
    isNew: true,
    supports3d: true,
    supports360: false,
    supportsAr: true,
    modelGlbUrl: SAMPLE_GLB.helmet,
    modelUsdzUrl: null,
    fallbackImageUrl:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&q=80",
    images: [
      { id: "img4", productId: "p4", url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200&q=80", altText: "Halo X13", sortOrder: 0, isPrimary: true },
    ],
    options: [
      { id: "opt4", productId: "p4", name: "ความจุ", displayType: "buttons", sortOrder: 0, values: [
        { id: "ov7", optionId: "opt4", value: "256GB", sortOrder: 0 },
        { id: "ov8", optionId: "opt4", value: "512GB", sortOrder: 1 },
      ]},
      { id: "opt4b", productId: "p4", name: "สี", displayType: "color", sortOrder: 1, values: [
        { id: "ov9", optionId: "opt4b", value: "ไทเทเนียม", colorHex: "#7c7f85", sortOrder: 0 },
        { id: "ov10", optionId: "opt4b", value: "กราไฟต์", colorHex: "#2b2d33", sortOrder: 1 },
      ]},
    ],
    variants: [
      { id: "v7", productId: "p4", sku: "HLO-X13-256-TI", price: 21990, compareAtPrice: 24990, stockQuantity: 10, imageUrl: null, modelUrl: SAMPLE_GLB.helmet, isActive: true, optionValueIds: ["ov7", "ov9"] },
      { id: "v8", productId: "p4", sku: "HLO-X13-512-TI", price: 25990, compareAtPrice: 27990, stockQuantity: 5, imageUrl: null, modelUrl: SAMPLE_GLB.helmet, isActive: true, optionValueIds: ["ov8", "ov9"] },
      { id: "v9", productId: "p4", sku: "HLO-X13-256-GR", price: 21990, compareAtPrice: 24990, stockQuantity: 3, imageUrl: null, modelUrl: SAMPLE_GLB.helmet, isActive: true, optionValueIds: ["ov7", "ov10"] },
    ],
    hotspots: [
      { id: "h4", productId: "p4", title: "กล้องหลัก 3 ตัว", description: "เลนส์หลัก 50MP, อัลตร้าไวด์ 12MP, เทเลโฟโต้ 10MP ซูมออปติคัล 3 เท่า", position: { x: -0.2, y: 0.3, z: 0.3 }, normal: { x: 0, y: 0, z: 1 }, icon: "Camera", sortOrder: 0, isActive: true },
      { id: "h5", productId: "p4", title: "พอร์ต USB-C ชาร์จเร็ว", description: "รองรับชาร์จเร็ว 67W ชาร์จเต็ม 100% ใน 42 นาที", position: { x: 0, y: -0.4, z: 0 }, normal: { x: 0, y: -1, z: 0 }, icon: "Zap", sortOrder: 1, isActive: true },
    ],
    threeSixty: null,
    specs: [
      { label: "หน้าจอ", value: "6.7\" AMOLED 120Hz" },
      { label: "ชิปประมวลผล", value: "Octa-core 3.2GHz" },
      { label: "แบตเตอรี่", value: "5000mAh ชาร์จเร็ว 67W" },
      { label: "กันน้ำ", value: "IP68" },
    ],
    dimensions: { widthCm: 7.6, heightCm: 16.2, depthCm: 0.8, weightKg: 0.198 },
    reviewSummary: { average: 4.8, count: 342 },
    soldCount: 2100,
    shippingEtaDays: [1, 2],
    createdAt: now,
  },
  {
    id: "p5",
    name: "Throne Elite Gaming Chair",
    slug: "throne-elite-gaming-chair",
    shortDescription: "เก้าอี้เกมมิงหนัง PU รองรับสรีระ ปรับเอนได้ 165 องศา",
    description:
      "Throne Elite ออกแบบตามหลักสรีระศาสตร์ รองรับหลังส่วนล่างและคอ ปรับความสูง เอน และวางแขนได้หลายทิศทาง โครงเหล็กรับน้ำหนักได้ถึง 150 กก.",
    brand: "Throne",
    category: "เฟอร์นิเจอร์",
    categorySlug: "furniture",
    status: "active",
    basePrice: 6990,
    compareAtPrice: 8990,
    sku: "THR-CHR-ELT",
    stockQuantity: 15,
    lowStockThreshold: 5,
    isFeatured: false,
    isBestseller: true,
    isNew: false,
    supports3d: true,
    supports360: false,
    supportsAr: true,
    modelGlbUrl: SAMPLE_GLB.robot,
    modelUsdzUrl: null,
    fallbackImageUrl:
      "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=1200&q=80",
    images: [
      { id: "img5", productId: "p5", url: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=1200&q=80", altText: "Throne Elite Gaming Chair", sortOrder: 0, isPrimary: true },
    ],
    options: [
      { id: "opt5", productId: "p5", name: "สี", displayType: "color", sortOrder: 0, values: [
        { id: "ov11", optionId: "opt5", value: "ดำแดง", colorHex: "#7f1d1d", sortOrder: 0 },
        { id: "ov12", optionId: "opt5", value: "ดำน้ำเงิน", colorHex: "#1d4ed8", sortOrder: 1 },
      ]},
    ],
    variants: [
      { id: "v10", productId: "p5", sku: "THR-CHR-ELT-RD", price: 6990, compareAtPrice: 8990, stockQuantity: 8, imageUrl: null, modelUrl: SAMPLE_GLB.robot, isActive: true, optionValueIds: ["ov11"] },
      { id: "v11", productId: "p5", sku: "THR-CHR-ELT-BL", price: 6990, compareAtPrice: 8990, stockQuantity: 7, imageUrl: null, modelUrl: SAMPLE_GLB.robot, isActive: true, optionValueIds: ["ov12"] },
    ],
    hotspots: [
      { id: "h6", productId: "p5", title: "ปรับเอนได้ 165 องศา", description: "ล็อกมุมเอนได้หลายระดับ เหมาะกับการพักสายตาระหว่างเล่นเกม", position: { x: 0, y: -0.2, z: -0.3 }, normal: { x: 0, y: 0, z: -1 }, icon: "RockingChair", sortOrder: 0, isActive: true },
    ],
    threeSixty: null,
    specs: [
      { label: "วัสดุ", value: "หนัง PU เกรดพรีเมียม" },
      { label: "รับน้ำหนักสูงสุด", value: "150 กก." },
      { label: "ปรับความสูง", value: "Gas Lift Class 4" },
    ],
    dimensions: { widthCm: 70, heightCm: 130, depthCm: 70, weightKg: 22 },
    reviewSummary: { average: 4.5, count: 58 },
    soldCount: 190,
    shippingEtaDays: [3, 6],
    createdAt: now,
  },
  {
    id: "p6",
    name: "Strider Runner Sneaker",
    slug: "strider-runner-sneaker",
    shortDescription: "รองเท้าวิ่งพื้นรองรับแรงกระแทก น้ำหนักเบา ระบายอากาศดี",
    description:
      "Strider Runner ใช้พื้นโฟม EVA ผสมเจลรองรับแรงกระแทกทุกย่างก้าว ผ้าตาข่ายระบายอากาศ เหมาะกับการวิ่งระยะไกลและใส่ในชีวิตประจำวัน",
    brand: "Strider",
    category: "รองเท้า",
    categorySlug: "shoes",
    status: "active",
    basePrice: 2290,
    compareAtPrice: 2890,
    sku: "STR-SNK-RUN",
    stockQuantity: 80,
    lowStockThreshold: 20,
    isFeatured: false,
    isBestseller: true,
    isNew: false,
    supports3d: false,
    supports360: true,
    supportsAr: false,
    modelGlbUrl: null,
    modelUsdzUrl: null,
    fallbackImageUrl:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&q=80",
    images: [
      { id: "img6", productId: "p6", url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&q=80", altText: "Strider Runner Sneaker", sortOrder: 0, isPrimary: true },
    ],
    options: [
      { id: "opt6", productId: "p6", name: "ไซซ์", displayType: "buttons", sortOrder: 0, values: [
        { id: "ov13", optionId: "opt6", value: "40", sortOrder: 0 },
        { id: "ov14", optionId: "opt6", value: "41", sortOrder: 1 },
        { id: "ov15", optionId: "opt6", value: "42", sortOrder: 2 },
        { id: "ov16", optionId: "opt6", value: "43", sortOrder: 3 },
      ]},
    ],
    variants: [
      { id: "v12", productId: "p6", sku: "STR-SNK-RUN-40", price: 2290, compareAtPrice: 2890, stockQuantity: 20, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov13"] },
      { id: "v13", productId: "p6", sku: "STR-SNK-RUN-41", price: 2290, compareAtPrice: 2890, stockQuantity: 25, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov14"] },
      { id: "v14", productId: "p6", sku: "STR-SNK-RUN-42", price: 2290, compareAtPrice: 2890, stockQuantity: 25, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov15"] },
      { id: "v15", productId: "p6", sku: "STR-SNK-RUN-43", price: 2290, compareAtPrice: 2890, stockQuantity: 10, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov16"] },
    ],
    hotspots: [],
    threeSixty: { frameCount: 24, frames: Array.from({ length: 24 }, (_, i) => `/product-360/sneaker/frame-${String(i + 1).padStart(3, "0")}.webp`) },
    specs: [
      { label: "พื้นรองเท้า", value: "EVA Foam + Gel" },
      { label: "วัสดุด้านบน", value: "ผ้าตาข่ายระบายอากาศ" },
      { label: "น้ำหนัก (ไซซ์ 42)", value: "260 กรัม" },
    ],
    dimensions: { widthCm: 12, heightCm: 11, depthCm: 30, weightKg: 0.26 },
    reviewSummary: { average: 4.4, count: 96 },
    soldCount: 540,
    shippingEtaDays: [2, 4],
    createdAt: now,
  },
  {
    id: "p7",
    name: "Voyage Travel Backpack",
    slug: "voyage-travel-backpack",
    shortDescription: "กระเป๋าเป้กันน้ำ 30L ช่องใส่โน้ตบุ๊ก 16 นิ้ว",
    description:
      "Voyage ผลิตจากผ้าไนลอนกันน้ำ ทนทานต่อการใช้งานหนัก มีช่องใส่โน้ตบุ๊กบุนวมแยกส่วน ช่องเก็บของหลายขนาดจัดระเบียบง่าย",
    brand: "Voyage",
    category: "กระเป๋า",
    categorySlug: "bags",
    status: "active",
    basePrice: 1590,
    compareAtPrice: null,
    sku: "VYG-BAG-30L",
    stockQuantity: 55,
    lowStockThreshold: 15,
    isFeatured: false,
    isBestseller: false,
    isNew: true,
    supports3d: false,
    supports360: false,
    supportsAr: false,
    modelGlbUrl: null,
    modelUsdzUrl: null,
    fallbackImageUrl:
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1200&q=80",
    images: [
      { id: "img7", productId: "p7", url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1200&q=80", altText: "Voyage Travel Backpack", sortOrder: 0, isPrimary: true },
    ],
    options: [
      { id: "opt7", productId: "p7", name: "สี", displayType: "color", sortOrder: 0, values: [
        { id: "ov17", optionId: "opt7", value: "ดำ", colorHex: "#14161b", sortOrder: 0 },
        { id: "ov18", optionId: "opt7", value: "เขียวทหาร", colorHex: "#3f4a3d", sortOrder: 1 },
      ]},
    ],
    variants: [
      { id: "v16", productId: "p7", sku: "VYG-BAG-30L-BLK", price: 1590, compareAtPrice: null, stockQuantity: 35, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov17"] },
      { id: "v17", productId: "p7", sku: "VYG-BAG-30L-GRN", price: 1590, compareAtPrice: null, stockQuantity: 20, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov18"] },
    ],
    hotspots: [],
    threeSixty: null,
    specs: [
      { label: "ความจุ", value: "30 ลิตร" },
      { label: "วัสดุ", value: "ไนลอนกันน้ำ 900D" },
      { label: "ช่องโน้ตบุ๊ก", value: "รองรับสูงสุด 16 นิ้ว" },
    ],
    dimensions: { widthCm: 32, heightCm: 48, depthCm: 20, weightKg: 0.95 },
    reviewSummary: { average: 4.3, count: 41 },
    soldCount: 220,
    shippingEtaDays: [2, 4],
    createdAt: now,
  },
  {
    id: "p8",
    name: "Pulse Smartwatch Series 5",
    slug: "pulse-smartwatch-series-5",
    shortDescription: "นาฬิกาอัจฉริยะวัดชีพจร ออกซิเจนในเลือด กันน้ำ 5ATM",
    description:
      "Pulse Series 5 ติดตามสุขภาพครบวงจร วัดอัตราการเต้นหัวใจ ออกซิเจนในเลือด การนอนหลับ พร้อมโหมดออกกำลังกายกว่า 100 โหมด แบตอึด 7 วัน",
    brand: "Pulse",
    category: "โทรศัพท์และแท็บเล็ต",
    categorySlug: "phones-tablets",
    status: "active",
    basePrice: 3990,
    compareAtPrice: 4990,
    sku: "PLS-WCH-S5",
    stockQuantity: 34,
    lowStockThreshold: 10,
    isFeatured: true,
    isBestseller: false,
    isNew: true,
    supports3d: false,
    supports360: true,
    supportsAr: false,
    modelGlbUrl: null,
    modelUsdzUrl: null,
    fallbackImageUrl:
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=1200&q=80",
    images: [
      { id: "img8", productId: "p8", url: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=1200&q=80", altText: "Pulse Smartwatch", sortOrder: 0, isPrimary: true },
    ],
    options: [
      { id: "opt8", productId: "p8", name: "สายนาฬิกา", displayType: "color", sortOrder: 0, values: [
        { id: "ov19", optionId: "opt8", value: "ดำ", colorHex: "#15171c", sortOrder: 0 },
        { id: "ov20", optionId: "opt8", value: "ชมพูโรสโกลด์", colorHex: "#e6b3a3", sortOrder: 1 },
      ]},
    ],
    variants: [
      { id: "v18", productId: "p8", sku: "PLS-WCH-S5-BLK", price: 3990, compareAtPrice: 4990, stockQuantity: 20, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov19"] },
      { id: "v19", productId: "p8", sku: "PLS-WCH-S5-RG", price: 4190, compareAtPrice: 5190, stockQuantity: 14, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov20"] },
    ],
    hotspots: [],
    threeSixty: { frameCount: 24, frames: Array.from({ length: 24 }, (_, i) => `/product-360/smartwatch/frame-${String(i + 1).padStart(3, "0")}.webp`) },
    specs: [
      { label: "หน้าจอ", value: "1.43\" AMOLED" },
      { label: "กันน้ำ", value: "5ATM" },
      { label: "แบตเตอรี่", value: "ใช้งานได้นานสูงสุด 7 วัน" },
    ],
    dimensions: { widthCm: 4.1, heightCm: 4.5, depthCm: 1.1, weightKg: 0.038 },
    reviewSummary: { average: 4.6, count: 167 },
    soldCount: 980,
    shippingEtaDays: [1, 3],
    createdAt: now,
  },
  {
    id: "p9",
    name: "Echo Dome Bluetooth Speaker",
    slug: "echo-dome-bluetooth-speaker",
    shortDescription: "ลำโพงบลูทูธเสียงรอบทิศทาง กันน้ำ IPX7 แบตอึด 24 ชม.",
    description:
      "Echo Dome ให้เสียงกระจายรอบทิศทาง 360 องศา ดีไซน์ทรงโดมกะทัดรัด กันน้ำกันฝุ่นระดับ IPX7 พกพาสะดวกเหมาะกับกิจกรรมกลางแจ้ง",
    brand: "Echo",
    category: "หูฟังและลำโพง",
    categorySlug: "audio",
    status: "active",
    basePrice: 1790,
    compareAtPrice: 2190,
    sku: "ECH-SPK-DOME",
    stockQuantity: 48,
    lowStockThreshold: 12,
    isFeatured: false,
    isBestseller: true,
    isNew: false,
    supports3d: false,
    supports360: true,
    supportsAr: false,
    modelGlbUrl: null,
    modelUsdzUrl: null,
    fallbackImageUrl:
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=1200&q=80",
    images: [
      { id: "img9", productId: "p9", url: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=1200&q=80", altText: "Echo Dome Speaker", sortOrder: 0, isPrimary: true },
    ],
    options: [
      { id: "opt9", productId: "p9", name: "สี", displayType: "color", sortOrder: 0, values: [
        { id: "ov21", optionId: "opt9", value: "ดำ", colorHex: "#191b20", sortOrder: 0 },
        { id: "ov22", optionId: "opt9", value: "ฟ้า", colorHex: "#3b82f6", sortOrder: 1 },
      ]},
    ],
    variants: [
      { id: "v20", productId: "p9", sku: "ECH-SPK-DOME-BLK", price: 1790, compareAtPrice: 2190, stockQuantity: 30, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov21"] },
      { id: "v21", productId: "p9", sku: "ECH-SPK-DOME-BLU", price: 1790, compareAtPrice: 2190, stockQuantity: 18, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: ["ov22"] },
    ],
    hotspots: [],
    threeSixty: { frameCount: 24, frames: Array.from({ length: 24 }, (_, i) => `/product-360/bt-speaker/frame-${String(i + 1).padStart(3, "0")}.webp`) },
    specs: [
      { label: "กำลังขับ", value: "20W RMS" },
      { label: "กันน้ำ", value: "IPX7" },
      { label: "แบตเตอรี่", value: "24 ชั่วโมง" },
    ],
    dimensions: { widthCm: 10, heightCm: 10, depthCm: 10, weightKg: 0.52 },
    reviewSummary: { average: 4.5, count: 89 },
    soldCount: 610,
    shippingEtaDays: [1, 3],
    createdAt: now,
  },
  {
    id: "p10",
    name: "Lumen Adjustable Desk Lamp",
    slug: "lumen-adjustable-desk-lamp",
    shortDescription: "โคมไฟตั้งโต๊ะปรับแสงได้ ถนอมสายตา ชาร์จผ่าน USB-C",
    description:
      "Lumen ให้แสงสม่ำเสมอไม่กระพริบ ปรับความสว่างและอุณหภูมิสีได้ตามต้องการ แขนปรับได้หลายองศาเหมาะกับโต๊ะทำงานและโต๊ะอ่านหนังสือ",
    brand: "Lumen",
    category: "ของแต่งบ้าน",
    categorySlug: "home-decor",
    status: "active",
    basePrice: 990,
    compareAtPrice: 1290,
    sku: "LMN-LMP-ADJ",
    stockQuantity: 70,
    lowStockThreshold: 20,
    isFeatured: false,
    isBestseller: false,
    isNew: false,
    supports3d: false,
    supports360: false,
    supportsAr: false,
    modelGlbUrl: null,
    modelUsdzUrl: null,
    fallbackImageUrl:
      "https://images.unsplash.com/photo-1524634126442-357e0eac3c14?w=1200&q=80",
    images: [
      { id: "img10", productId: "p10", url: "https://images.unsplash.com/photo-1524634126442-357e0eac3c14?w=1200&q=80", altText: "Lumen Desk Lamp", sortOrder: 0, isPrimary: true },
    ],
    options: [],
    variants: [
      { id: "v22", productId: "p10", sku: "LMN-LMP-ADJ-01", price: 990, compareAtPrice: 1290, stockQuantity: 70, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: [] },
    ],
    hotspots: [],
    threeSixty: null,
    specs: [
      { label: "กำลังไฟ", value: "10W LED" },
      { label: "การชาร์จ", value: "USB-C" },
      { label: "โหมดแสง", value: "3 อุณหภูมิสี x 10 ระดับความสว่าง" },
    ],
    dimensions: { widthCm: 15, heightCm: 45, depthCm: 18, weightKg: 0.65 },
    reviewSummary: { average: 4.2, count: 33 },
    soldCount: 150,
    shippingEtaDays: [2, 5],
    createdAt: now,
  },
  {
    id: "p11",
    name: "Guardian Mecha Collectible Figure",
    slug: "guardian-mecha-collectible-figure",
    shortDescription: "ฟิกเกอร์หุ่นยนต์ขนาด 25 ซม. ขยับข้อต่อได้ พร้อมฐานตั้งโชว์",
    description:
      "Guardian Mecha รายละเอียดสูง ปั้นและทาสีด้วยมือ ข้อต่อขยับได้หลายจุดสำหรับจัดท่า มาพร้อมฐานตั้งโชว์ไฟ LED",
    brand: "Collectors Lab",
    category: "ฟิกเกอร์และของสะสม",
    categorySlug: "collectibles",
    status: "active",
    basePrice: 4590,
    compareAtPrice: null,
    sku: "CLB-FIG-MECHA",
    stockQuantity: 12,
    lowStockThreshold: 5,
    isFeatured: true,
    isBestseller: false,
    isNew: true,
    supports3d: true,
    supports360: false,
    supportsAr: true,
    modelGlbUrl: SAMPLE_GLB.astronaut,
    modelUsdzUrl: null,
    fallbackImageUrl:
      "https://images.unsplash.com/photo-1608889175123-8ee362201f81?w=1200&q=80",
    images: [
      { id: "img11", productId: "p11", url: "https://images.unsplash.com/photo-1608889175123-8ee362201f81?w=1200&q=80", altText: "Guardian Mecha Figure", sortOrder: 0, isPrimary: true },
    ],
    options: [],
    variants: [
      { id: "v23", productId: "p11", sku: "CLB-FIG-MECHA-01", price: 4590, compareAtPrice: null, stockQuantity: 12, imageUrl: null, modelUrl: SAMPLE_GLB.astronaut, isActive: true, optionValueIds: [] },
    ],
    hotspots: [
      { id: "h7", productId: "p11", title: "ข้อต่อขยับได้ 20 จุด", description: "จัดท่าทางได้อย่างอิสระโดยไม่ทำสีลอก", position: { x: 0.1, y: 0.3, z: 0.2 }, normal: { x: 0, y: 1, z: 0 }, icon: "Move3d", sortOrder: 0, isActive: true },
      { id: "h8", productId: "p11", title: "ฐานไฟ LED", description: "ฐานตั้งโชว์พร้อมไฟ LED เปลี่ยนสีได้ ใช้พลังงานจาก USB", position: { x: 0, y: -0.45, z: 0 }, normal: { x: 0, y: -1, z: 0 }, icon: "Lightbulb", sortOrder: 1, isActive: true },
    ],
    threeSixty: null,
    specs: [
      { label: "ความสูง", value: "25 ซม." },
      { label: "วัสดุ", value: "PVC + ABS" },
      { label: "จุดข้อต่อ", value: "20 จุด" },
    ],
    dimensions: { widthCm: 15, heightCm: 25, depthCm: 12, weightKg: 0.72 },
    reviewSummary: { average: 4.9, count: 27 },
    soldCount: 95,
    shippingEtaDays: [3, 7],
    createdAt: now,
  },
  {
    id: "p12",
    name: "Levit Aluminum Laptop Stand",
    slug: "levit-aluminum-laptop-stand",
    shortDescription: "ขาตั้งโน้ตบุ๊กอะลูมิเนียม พับเก็บได้ ปรับความสูงได้ 6 ระดับ",
    description:
      "Levit ผลิตจากอะลูมิเนียมชิ้นเดียวแข็งแรง น้ำหนักเบาพกพาง่าย ปรับมุมและความสูงได้เพื่อสรีระที่เหมาะสม ระบายความร้อนโน้ตบุ๊กได้ดีขึ้น",
    brand: "Levit",
    category: "คอมพิวเตอร์",
    categorySlug: "computers",
    status: "active",
    basePrice: 890,
    compareAtPrice: 1190,
    sku: "LVT-STD-ALU",
    stockQuantity: 90,
    lowStockThreshold: 20,
    isFeatured: false,
    isBestseller: true,
    isNew: false,
    supports3d: false,
    supports360: false,
    supportsAr: false,
    modelGlbUrl: null,
    modelUsdzUrl: null,
    fallbackImageUrl:
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=1200&q=80",
    images: [
      { id: "img12", productId: "p12", url: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=1200&q=80", altText: "Levit Laptop Stand", sortOrder: 0, isPrimary: true },
    ],
    options: [],
    variants: [
      { id: "v24", productId: "p12", sku: "LVT-STD-ALU-01", price: 890, compareAtPrice: 1190, stockQuantity: 90, imageUrl: null, modelUrl: null, isActive: true, optionValueIds: [] },
    ],
    hotspots: [],
    threeSixty: null,
    specs: [
      { label: "วัสดุ", value: "อะลูมิเนียมอัลลอย" },
      { label: "รองรับขนาดจอ", value: "10 - 17 นิ้ว" },
      { label: "รับน้ำหนักสูงสุด", value: "5 กก." },
    ],
    dimensions: { widthCm: 25, heightCm: 15, depthCm: 3, weightKg: 0.68 },
    reviewSummary: { average: 4.4, count: 112 },
    soldCount: 780,
    shippingEtaDays: [1, 3],
    createdAt: now,
  },
];

export function getMockProductBySlug(slug: string) {
  return MOCK_PRODUCTS.find((p) => p.slug === slug) ?? null;
}
