import { useTranslation } from "@/lib/i18n/locale-provider";

const messages = {
  en: {
    title: "Interactive Studio", subtitle: "Explore every detail, your way.", modes: "Product view", image: "Images", spin: "360° view", model: "3D Studio", ar: "AR preview",
    dimensions: "Dimensions", dimensionOrder: "Width × height × depth", unknownDimensions: "Dimensions are not available for this product.", dimensionNote: "Product specifications; the preview is not a scale reference.", color: "Studio color", selected: "Selected finish", imageNote: "Photos show the available product images. A matching photo may not exist for every finish.", sample: "Illustrative sample model — not a scan of this product. Shape, finish and AR size may differ.",
    loading: "Loading 3D preview…", failed: "3D could not load. Showing the product image.", retry: "Try 3D again", drag: "Drag to rotate · Scroll or pinch to zoom", rotate: "Auto rotate", pause: "Pause rotation", reset: "Reset view", full: "Full screen", exitFull: "Exit full screen", background: "Background", neutral: "Neutral", dark: "Midnight", light: "Light", lighting: "Lighting", arLaunch: "View in your space", arUnavailable: "AR is not available on this device. You can still explore in 3D.", arNote: "AR needs a supported phone and browser. External AR viewers may show the original model finish.", arFailed: "AR could not start. Try a supported mobile browser.", features: "Product details", noModel: "A 3D model is not available for this product.", photo: "View image", material: "Finish preview", materialNote: "Preview colors are illustrative and may differ from the physical finish.",
  },
  th: {
    title: "สตูดิโอสินค้า", subtitle: "สำรวจทุกรายละเอียดในมุมที่คุณเลือก", modes: "รูปแบบการแสดงสินค้า", image: "รูปภาพ", spin: "ดู 360°", model: "สตูดิโอ 3D", ar: "ดูตัวอย่าง AR",
    dimensions: "ขนาดสินค้า", dimensionOrder: "กว้าง × สูง × ลึก", unknownDimensions: "ยังไม่มีข้อมูลขนาดสำหรับสินค้านี้", dimensionNote: "ขนาดตามข้อมูลสินค้า ภาพตัวอย่างไม่ใช่มาตราส่วนอ้างอิง", color: "สีในสตูดิโอ", selected: "สีที่เลือก", imageNote: "แสดงภาพสินค้าที่มีอยู่ ภาพอาจไม่ตรงกับทุกสีที่เลือก", sample: "โมเดลสาธิต ไม่ใช่โมเดลสแกนของสินค้านี้ รูปทรง สี และขนาดใน AR อาจแตกต่างจากสินค้าจริง",
    loading: "กำลังโหลดตัวอย่าง 3D…", failed: "โหลด 3D ไม่สำเร็จ กำลังแสดงรูปสินค้าแทน", retry: "ลองโหลด 3D อีกครั้ง", drag: "ลากเพื่อหมุน · เลื่อนหรือจีบนิ้วเพื่อซูม", rotate: "หมุนอัตโนมัติ", pause: "หยุดหมุน", reset: "รีเซ็ตมุมมอง", full: "เต็มจอ", exitFull: "ออกจากเต็มจอ", background: "พื้นหลัง", neutral: "กลาง", dark: "มิดไนต์", light: "สว่าง", lighting: "แสงสว่าง", arLaunch: "ดูในพื้นที่ของคุณ", arUnavailable: "อุปกรณ์นี้ไม่รองรับ AR คุณยังสำรวจโมเดล 3D ได้", arNote: "AR ต้องใช้โทรศัพท์และเบราว์เซอร์ที่รองรับ แอป AR ภายนอกอาจแสดงสีต้นฉบับของโมเดล", arFailed: "เปิด AR ไม่สำเร็จ ลองเปิดด้วยเบราว์เซอร์บนมือถือที่รองรับ", features: "รายละเอียดสินค้า", noModel: "ยังไม่มีโมเดล 3D สำหรับสินค้านี้", photo: "ดูรูปที่", material: "ตัวอย่างพื้นผิว", materialNote: "สีตัวอย่างใช้เพื่อประกอบการเลือกและอาจแตกต่างจากพื้นผิวจริง",
  },
};
export function useStudioMessages() { return messages[useTranslation().locale]; }
